### ISSUE TITLE
Can't Run Tests

### ISSUE THREAD

**Issue by pyrmont** [ruby/racc#117]
Hi, I'm running Ruby 2.6.4 via chruby. I clone this repository and then run `bundle install --path vendor`. I then run `bundle exec rake`. I get the following error:

```
** History.txt is missing or in the wrong format for auto-intuiting.
   run `sow blah` and look at its text files
mkdir -p tmp/x86_64-linux/cparse/2.6.4
cd tmp/x86_64-linux/cparse/2.6.4
/[...]/.rubies/ruby-2.6.4/bin/ruby -I. ../../../../ext/racc/extconf.rb
checking for rb_ary_subseq()... yes
creating Makefile
cd -
cd tmp/x86_64-linux/cparse/2.6.4
/usr/bin/make
compiling ../../../../ext/racc/cparse.c
linking shared-object racc/cparse.so
cd -
mkdir -p tmp/x86_64-linux/stage/lib/racc
cp COPYING tmp/x86_64-linux/stage/COPYING
cp DEPENDS tmp/x86_64-linux/stage/DEPENDS
cp Manifest.txt tmp/x86_64-linux/stage/Manifest.txt
cp README.ja.rdoc tmp/x86_64-linux/stage/README.ja.rdoc
cp README.rdoc tmp/x86_64-linux/stage/README.rdoc
cp Rakefile tmp/x86_64-linux/stage/Rakefile
cp TODO tmp/x86_64-linux/stage/TODO
mkdir -p tmp/x86_64-linux/stage/bin
cp bin/racc tmp/x86_64-linux/stage/bin/racc
mkdir -p tmp/x86_64-linux/stage/ext/racc
cp ext/racc/MANIFEST tmp/x86_64-linux/stage/ext/racc/MANIFEST
mkdir -p tmp/x86_64-linux/stage/ext/racc/com/headius/racc
cp ext/racc/com/headius/racc/Cparse.java tmp/x86_64-linux/stage/ext/racc/com/headius/racc/Cparse.java
cp ext/racc/cparse.c tmp/x86_64-linux/stage/ext/racc/cparse.c
cp ext/racc/depend tmp/x86_64-linux/stage/ext/racc/depend
cp ext/racc/extconf.rb tmp/x86_64-linux/stage/ext/racc/extconf.rb
cp lib/racc.rb tmp/x86_64-linux/stage/lib/racc.rb
cp lib/racc/color.rb tmp/x86_64-linux/stage/lib/racc/color.rb
cp lib/racc/directed_graph.rb tmp/x86_64-linux/stage/lib/racc/directed_graph.rb
cp lib/racc/dsl.rb tmp/x86_64-linux/stage/lib/racc/dsl.rb
cp lib/racc/exception.rb tmp/x86_64-linux/stage/lib/racc/exception.rb
cp lib/racc/grammar.rb tmp/x86_64-linux/stage/lib/racc/grammar.rb
cp lib/racc/grammar_file_parser.rb tmp/x86_64-linux/stage/lib/racc/grammar_file_parser.rb
ragel -F1 -R lib/racc/grammar_file_scanner.rl -o lib/racc/grammar_file_scanner.rb
rake aborted!
Command failed with status (127): [ragel -F1 -R lib/racc/grammar_file_scanner...]
/[...]/development/racc/Rakefile:115:in `block in <top (required)>'
/[...]/development/racc/vendor/ruby/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/[...]/.gem/ruby/2.6.4/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
/[...]/.gem/ruby/2.6.4/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/[...]/.gem/ruby/2.6.4/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
/[...]/.gem/ruby/2.6.4/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
/[...]/.gem/ruby/2.6.4/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/[...]/.gem/ruby/2.6.4/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/[...]/.gem/ruby/2.6.4/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/[...]/.gem/ruby/2.6.4/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
/[...]/.gem/ruby/2.6.4/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/[...]/.gem/ruby/2.6.4/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
/[...]/.gem/ruby/2.6.4/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
/[...]/.gem/ruby/2.6.4/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/[...]/.gem/ruby/2.6.4/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
/[...]/.gem/ruby/2.6.4/bin/bundle:23:in `load'
/[...]/.gem/ruby/2.6.4/bin/bundle:23:in `<main>'
Tasks: TOP => default => test => compile => compile:x86_64-linux => compile:cparse:x86_64-linux => copy:cparse:x86_64-linux:2.6.4 => tmp/x86_64-linux/stage/lib/racc/grammar_file_scanner.rb => lib/racc/grammar_file_scanner.rb
(See full trace by running task with --trace)
```

What am I doing wrong? I've tried running `bundle exec sow blah` but I don't understand what I'm supposed to do with the files that it generates.

**Comment by alexdowad** [comment]
Probably you don't have ragel installed. It's trying to generate a source
file using using ragel but failing to do so.

**Comment by pyrmont** [comment]
Thanks @alexdowad! That was indeed my problem!
