### ISSUE TITLE
Cannot install racc on the fresh Ubuntu 20.04

### ISSUE THREAD

**Issue by brykov** [ruby/racc#159]
So I have a fresh new fully updated Ubuntu Server 20.04.

```
5.4.0-1043-oracle #46-Ubuntu SMP Tue Apr 13 09:12:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Ruby is installed via apt:

```
# ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
```

Trying to install racc under root account gives me this: 

```
# gem install racc
Building native extensions. This could take a while...
ERROR:  Error installing racc:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.7.0/gems/racc-1.5.2/ext/racc/cparse
/usr/bin/ruby2.7 -I /usr/lib/ruby/2.7.0 -r ./siteconf20210510-20466-xw2e2p.rb extconf.rb
checking for rb_ary_subseq()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.7
/usr/lib/ruby/2.7.0/mkmf.rb:471:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/lib/ruby/2.7.0/mkmf.rb:564:in `try_link0'
	from /usr/lib/ruby/2.7.0/mkmf.rb:582:in `try_link'
	from /usr/lib/ruby/2.7.0/mkmf.rb:794:in `try_func'
	from /usr/lib/ruby/2.7.0/mkmf.rb:1083:in `block in have_func'
	from /usr/lib/ruby/2.7.0/mkmf.rb:971:in `block in checking_for'
	from /usr/lib/ruby/2.7.0/mkmf.rb:361:in `block (2 levels) in postpone'
	from /usr/lib/ruby/2.7.0/mkmf.rb:331:in `open'
	from /usr/lib/ruby/2.7.0/mkmf.rb:361:in `block in postpone'
	from /usr/lib/ruby/2.7.0/mkmf.rb:331:in `open'
	from /usr/lib/ruby/2.7.0/mkmf.rb:357:in `postpone'
	from /usr/lib/ruby/2.7.0/mkmf.rb:970:in `checking_for'
	from /usr/lib/ruby/2.7.0/mkmf.rb:1082:in `have_func'
	from extconf.rb:6:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.7.0/extensions/x86_64-linux/2.7.0/racc-1.5.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.7.0/gems/racc-1.5.2 for inspection.
Results logged to /var/lib/gems/2.7.0/extensions/x86_64-linux/2.7.0/racc-1.5.2/gem_make.out
```

**Comment by brykov** [comment]
here is the mkmf.log contents:

```
# cat /var/lib/gems/2.7.0/extensions/x86_64-linux/2.7.0/racc-1.5.2/mkmf.log
"gcc -o conftest -I/usr/include/x86_64-linux-gnu/ruby-2.7.0 -I/usr/include/ruby-2.7.0/ruby/backward -I/usr/include/ruby-2.7.0 -I. -Wdate-time -D_FORTIFY_SOURCE=2   -g -O2 -fdebug-prefix-map=/build/ruby2.7-2E2p8v/ruby2.7-2.7.0=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC conftest.c  -L. -L/usr/lib/x86_64-linux-gnu -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -lruby-2.7  -lm   -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */
```

**Comment by brykov** [comment]
> @brykov Would
> 
> ```
> sudo apt install build-essential
> ```
> 
> help?

YES! So simple, yet effective. Thank you!
